language: objective-c
osx_image: xcode8.2
node_js:
  - "6"

before_script:
  - npm install -g swiftx

script:
  - swift build
  - xcodebuild -scheme Time build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - swiftx update-build-config --owner randymarsh77 --configPath builds/swift/config
  - swiftx update-dependency-graph --owner randymarsh77 --configPath builds/swift/config
  - swiftx trigger-downstream-builds --owner randymarsh77 --configPath builds/swift/config

after_failure:
  - swiftx trigger-downstream-builds --owner randymarsh77 --configPath builds/swift/config --force
